# Generated by Django 3.0.2 on 2020-01-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
