# Generated by Django 3.0.2 on 2020-01-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review_rate'),
        ('core', '0002_auto_20200111_1522'),
    ]

    operations = [
    ]
